[server]

port = 8502
enableStaticServing = true
maxMessageSize = 500

[browser]
serverPort = 8502

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
hideTopBar = true

[theme]

# # The preset Streamlit theme that your custom theme inherits from.
# # One of "light" or "dark".
# base =

# # Primary accent color for interactive elements.
primaryColor = "#CC5F33"

# # Background color for the main content area.
# backgroundColor = "#F9F5F4"

# # Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "#FCF2F2"

# # Color used for almost all text.
# textColor =

# # Font family for all text in the app, except code blocks. One of "sans serif",
# # "serif", or "monospace".
# font =


